#!/bin/bash

dir=${1?phabricator}

set -e

\cp -r $(dirname ${0})/src ${dir}/
map=${dir}/src/__phutil_library_map__.php
sed -i ":a;\$\!{N;ba};s/    'PhabricatorAutoEventListener' => 'infrastructure/events/PhabricatorAutoEventListener.php',/&\n    'PhabricatorAzureAuthProvider' => 'applications/auth/provider/PhabricatorAzureAuthProvider.php',/1" ${map}
sed -i ":a;\$\!{N;ba};s/    'PhabricatorAutoEventListener' => 'PhabricatorEventListener',/&\n    'PhabricatorAzureAuthProvider' => 'PhabricatorOAuth2AuthProvider',/3" ${map}
