#!/bin/bash

dir=${1?phabricator}

set -e

map=${dir}/src/__phutil_library_map__.php
sed -i ":a;\$\!{N;ba};s/.*PhabricatorAutoEventListener.*/&\n    'PhabricatorAzureAuthProvider' => 'applications/auth/provider/PhabricatorAzureAuthProvider.php',/1" ${map}
sed -i ":a;\$\!{N;ba};s/.*PhabricatorAutoEventListener.*/&\n    'PhabricatorAzureAuthProvider' => 'PhabricatorOAuth2AuthProvider',/3" ${map}
